// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Cookie struct {
	Host      string    `json:"host"`
	Cookies   string    `json:"cookies"`
	UpdatedAt time.Time `json:"updated_at"`
}
