name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: takumi3488/cookiejar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata (writer)
        id: meta-writer
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-writer

      - name: Build and push Docker image (writer)
        id: build-and-push-writer
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-writer:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}-writer:latest
          labels: ${{ steps.meta-writer.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          target: writer

      - name: Extract Docker metadata (reader)
        id: meta-reader
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-reader

      - name: Build and push Docker image (reader)
        id: build-and-push-reader
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-reader:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}-reader:latest
          labels: ${{ steps.meta-reader.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          target: reader

  buf-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Buf
        uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1
        with:
          setup_only: true

      - name: Push to Buf Registry
        run: buf push
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
